language: android

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - $HOME/android-sdk-dl
    - $HOME/android-sdk
    - $HOME/google-cloud-sdk/

before_script:
  - ./gradle/android/sdk-setup.sh
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
      ./gradle/firebase/install.sh;
    fi

script:
#  - ./library/gradle/main.sh
 - ./gradlew :pusher-platform-core:assemble :pusher-platform-core:test
 - ./gradlew :pusher-platform-android:assembleDebug :pusher-platform-android:junitPlatformTestDebug :pusher-platform-android:lintDebug :pusher-platform-android:jacocoTestReportDebug
 - ./gradlew codeCoverageReport
 - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
    ./gradle/firebase/auth.sh;
    ./gradle/firebase/runLibraryAndroidTests.sh;
   fi

after_success:
  # report coverage
  - bash <(curl -s https://codecov.io/bash)

android:
  components:
    - tools
    - build-tools-27.0.3
    - android-27
    - add-on
    - extra
    - sys-img-armeabi-v7a-android-26
  licenses:
    - 'android-sdk-preview-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

deploy:
  - provider: script
    script: ./gradlew uploadArchives
    on:
      tags: true
      branch: master
