language: android

# https://stackoverflow.com/a/47726910/458365
before_install:
- yes | sdkmanager "platforms;android-27"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

script: ./gradlew build

android:
  components:
    - tools
    - build-tools-27.0.3
    - android-27
    - add-on
    - extra
    - sys-img-armeabi-v7a-android-26
  licenses:
    - 'android-sdk-preview-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

deploy:
  - provider: script
    script: ./gradlew uploadArchives
    on:
      tags: true
      branch: master