language: android

before_install:
  # https://stackoverflow.com/a/47726910/458365
  - yes | sdkmanager "platforms;android-27"
  # gcloud set up
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - $HOME/android-sdk-dl
    - $HOME/android-sdk
    - $HOME/google-cloud-sdk/

script: ./gradlew build codeCoverageReport

after_success:
  # report coverage
  - bash <(curl -s https://codecov.io/bash)

android:
  components:
    - tools
    - build-tools-27.0.3
    - android-27
    - add-on
    - extra
    - sys-img-armeabi-v7a-android-26
  licenses:
    - 'android-sdk-preview-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

deploy:
  - provider: script
    script: ./gradlew uploadArchives
    on:
      tags: true
      branch: master